show-fixes = true
line-length = 180
[lint]
ignore = [
    # The following rules are conflicting with ruff formatter: https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
    "W191",   # https://docs.astral.sh/ruff/rules/tab-indentation/
    "E111",   # https://docs.astral.sh/ruff/rules/indentation-with-invalid-multiple/
    "Q000",   # https://docs.astral.sh/ruff/rules/bad-quotes-inline-string/
    "Q001",   # https://docs.astral.sh/ruff/rules/bad-quotes-multiline-string/
    "Q002",   # https://docs.astral.sh/ruff/rules/bad-quotes-docstring/
    "Q003",   # https://docs.astral.sh/ruff/rules/avoidable-escaped-quote/
    "COM812", # https://docs.astral.sh/ruff/rules/missing-trailing-comma/
    "PLR2004",
    "ARG002",
    "RUF012",
    "PLR0912",
]
select = [
    "ARG",
    "B",   # https://docs.astral.sh/ruff/rules/#flake8-bugbear-b
    "C4",  # https://docs.astral.sh/ruff/rules/#flake8-comprehensions-c4
    "COM", # https://docs.astral.sh/ruff/rules/#flake8-commas-com
    "E",
    "W",   # https://docs.astral.sh/ruff/rules/#pycodestyle-e-w
    "EXE", # https://docs.astral.sh/ruff/rules/#flake8-executable-exe
    "F",   # https://docs.astral.sh/ruff/rules/#pyflakes-f
    "FA",  # https://docs.astral.sh/ruff/rules/#flake8-future-annotations-fa
    "I",   # https://docs.astral.sh/ruff/rules/#isort-i
    "PGH", # https://docs.astral.sh/ruff/rules/#pygrep-hooks-pgh
    "PIE", # https://docs.astral.sh/ruff/rules/#flake8-pie-pie
    "PL",  # https://docs.astral.sh/ruff/rules/#pylint-pl
    "PT",  # https://docs.astral.sh/ruff/rules/#flake8-pytest-style-pt
    "PYI", # https://docs.astral.sh/ruff/rules/#flake8-pyi-pyi
    "Q",   # https://docs.astral.sh/ruff/rules/#flake8-quotes-q
    "RET", # https://docs.astral.sh/ruff/rules/#flake8-return-ret
    "RSE", # https://docs.astral.sh/ruff/rules/#flake8-raise-rse
    "RUF", # https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf
    "SIM", # https://docs.astral.sh/ruff/rules/#flake8-simplify-sim
    "T10", # https://docs.astral.sh/ruff/rules/#flake8-debugger-t10
    "UP",  # https://docs.astral.sh/ruff/rules/#pyupgrade-up
    #    "G", # https://docs.astral.sh/ruff/rules/#flake8-logging-format-g
]

[format]
line-ending = "lf"

[lint.isort]
known-first-party = ["notifiers_cli"]

[lint.pylint]
max-args = 6
